# Generated by Django 5.0.6 on 2024-09-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
