# Generated by Django 5.0.6 on 2024-10-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_userdata_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
